server:
  port: 8888
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arquitectura-de-Software-02-2023/server-config.git


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8715/eureka/

encrypt:
  key: arquitectura